name: Run tests

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: "cc-builds"
  cancel-in-progress: false

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Download system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake ninja-build build-essential \
          libssl-dev libffi-dev libbz2-dev \
          libsqlite3-dev liblzma-dev zlib1g-dev \
          clang llvm
    - name: setup pyenv
      uses: "gabrielfalcao/pyenv-action@v18"
      with:
        default: 3.12.8
        command: |
          pyenv global 3.12.8
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build dependencies
      run: |
        export PATH="$(pyenv root)/shims:$PATH"
        export CC=clang
        export CXX=clang++
        cd third_party
        build_folder_name="build_gh_actions" ./build_deps.sh
    - name: Configure and build
      run: |
        export PATH="$(pyenv root)/shims:$PATH"
        export CC=clang
        export CXX=clang++
        cmake -GNinja -S . -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build
    - name: Run tests
      run: |
        cd build
        ctest
